// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7odq5L90nzLNxHN-pv68fLFX_Mk2haU',
    appId: '1:431963727125:web:7b7b9e651d1bae1653b51c',
    messagingSenderId: '431963727125',
    projectId: 'kisaan-hisab',
    authDomain: 'kisaan-hisab.firebaseapp.com',
    storageBucket: 'kisaan-hisab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0AQMKLAaBK_3gp0ibG_mQA8b9J6IS5g',
    appId: '1:431963727125:android:0b85e3ce8e858b8153b51c',
    messagingSenderId: '431963727125',
    projectId: 'kisaan-hisab',
    storageBucket: 'kisaan-hisab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzrBVRx-UGH1j-AcJZAh1tKj5lhLcw5Fs',
    appId: '1:431963727125:ios:d6a42882d7d5f9fd53b51c',
    messagingSenderId: '431963727125',
    projectId: 'kisaan-hisab',
    storageBucket: 'kisaan-hisab.firebasestorage.app',
    iosBundleId: 'com.example.kisanHisab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzrBVRx-UGH1j-AcJZAh1tKj5lhLcw5Fs',
    appId: '1:431963727125:ios:d6a42882d7d5f9fd53b51c',
    messagingSenderId: '431963727125',
    projectId: 'kisaan-hisab',
    storageBucket: 'kisaan-hisab.firebasestorage.app',
    iosBundleId: 'com.example.kisanHisab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH7odq5L90nzLNxHN-pv68fLFX_Mk2haU',
    appId: '1:431963727125:web:1b1a4357fde633e953b51c',
    messagingSenderId: '431963727125',
    projectId: 'kisaan-hisab',
    authDomain: 'kisaan-hisab.firebaseapp.com',
    storageBucket: 'kisaan-hisab.firebasestorage.app',
  );
}
